data <- matrix(c(18, 22, 20, 2, 28, 40, 20, 10, 40), nrow = 3, byrow = TRUE)
rownames(data) <- c("5-6 years", "7-8 years", "9-10 years")
colnames(data) <- c("A", "B", "C")
cov_BC <- cov(data[, "B"], data[, "C"])
cat("Sample covariance between B and C:", cov_BC, "\n")
cov_matrix <- cov(data)
print("Sample covariance matrix:")
print(cov_matrix)
cor_BC <- cor(data[, "B"], data[, "C"])
cat("Sample correlation between B and C:", cor_BC, "\n")
cor_matrix <- cor(data)
print("Sample correlation matrix:")
print(cor_matrix)
