# Define the data for Class A and Class B
classA <- c(76, 35, 47, 64, 95, 66, 89, 36, 84,76, 35, 47, 64, 95, 66, 89, 36, 84)
classB <- c(51, 56, 84, 60, 59, 70, 63, 66, 50,51, 56, 84, 60, 59, 70, 63, 66, 50)
mean_classA <- mean(classA)
mean_classB <- mean(classB)
median_classA <- median(classA)
median_classB <- median(classB)
range_classA <- max(classA) - min(classA)
range_classB <- max(classB) - min(classB)
cat("Class A Mean:", mean_classA, "\n")
cat("Class B Mean:", mean_classB, "\n")
cat("Class A Median:", median_classA, "\n")
cat("Class B Median:", median_classB, "\n")
cat("Class A Range:", range_classA, "\n")
cat("Class B Range:", range_classB, "\n")
combined_data <- list(ClassA = classA, ClassB = classB)
boxplot(combined_data, main="Boxplot of Exam Scores", names=c("Class A", "Class B"), col=c("blue", "green"), horizontal=TRUE)
legend("topright", legend=c("Class A", "Class B"), fill=c("blue", "green"))
cat("Inferences:\n")
cat("1. Class A has a higher mean score than Class B.\n")
cat("2. Class A has a higher median score than Class B.\n")
cat("3. Class A has a larger range of scores than Class B.\n")

